### ISSUE TITLE
missing separator 

### ISSUE THREAD

**Issue by knoblochtobias** [v3l0c1r4pt0r/xSDM#14]
I tried to build, but got the following error:

$ ./configure 
>checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CHECK... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for inflate in -lz... yes
checking for mcrypt_module_open in -lmcrypt... no
Libmcrypt is required for this program

$ make
>Making all in src
make[1]: Entering directory '/home/xxx/xSDM/src'
Makefile:345: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
make[1]: Leaving directory '/home/xxx/xSDM/src'
Makefile:342: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by v3l0c1r4pt0r** [comment]
```
checking for mcrypt_module_open in -lmcrypt... no
Libmcrypt is required for this program
```
Please, read README before installing. Please!
