### ISSUE TITLE
Directory creation failed with errno: 2

### ISSUE THREAD

**Issue by ray4167** [v3l0c1r4pt0r/xSDM#15]
I'm having a problem when I try to unpack en_sql_server_2008_r2_developer_x86_x64_ia64_dvd_522665.01.sdc
it says
Opening SDC file...		[OK]
Verifying keyfile...		[OK]
Validating SDC header...	[OK]
Warning! This container contains more than one file. However this program can only extract first one. Check for updates!
I don't know why this message comes out because I used xSDM a lot and it never happened before.

**Comment by v3l0c1r4pt0r** [comment]
Have it unpacked the file? For now the program can only extract first file. Lately Microsoft started including md5 sum as second one. If you see extracted file, it is the same situation as in issue #4.

**Comment by ray4167** [comment]
Actualy, I just canceled when I saw that message, so I tried continuing after I saw your comment, however I can't see the extracted file. It says
Opening SDC file...		[OK]
Verifying keyfile...		[OK]
Validating SDC header...	[OK]
Warning! This container contains more than one file. However this program can only extract first one. Check for updates!
Checking file integrity...	[OK]
Decoding file name...		[OK]
src/xsdm: Directory '/home/ray/Linux-SDM-Downloader//SQL Server 2008 R2 Developer (x86, x64, ia64) - DVD (English)/1033_ENU_LP/ia64/1033' creation failed with errno: 2
Creating directory structure...

**Comment by v3l0c1r4pt0r** [comment]
Hmm, error 2 means EACCES. Are you sure, you got rights to create dir in current directory?

**Comment by v3l0c1r4pt0r** [comment]
You were unpacking in '/home/ray/Linux-SDM-Downloader/', right? I think I know, what happened and it is different error, not related to the warning above. It uses 3 nested dirs and mkdir tries to create them at once returning 'no such file or dir'. I will try to fix this ASAP.

**Comment by v3l0c1r4pt0r** [comment]
OK, I've fixed that, but I suppose this won't let you do what you want (if I've found same SDC file you used), because first file here is useless RTF file. Even though, closing this issue, now your problem is the same as is #4
