### ISSUE TITLE
xSDM-0.1.3-beta/src/xsdm': free(): invalid pointer

### ISSUE THREAD

**Issue by Trexium** [v3l0c1r4pt0r/xSDM#2]
Hi!

Im getting an error saying:
"*** Error in `xSDM-0.1.3-beta/src/xsdm': free(): invalid pointer: 0x00007f33b3caa406 ***
Unpacking file(s)...		Aborted (core dumped)"
When trying to unpack a sdc file.
The whole thing is here:

Opening SDC file...		[OK]
Verifying keyfile...		[OK]
Validating SDC header...	[OK]
Checking file integrity...	[OK]
Decoding file name...		[OK]
Creating directory structure...	[OK]
*** Error in `xSDM-0.1.3-beta/src/xsdm': free(): invalid pointer: 0x00007f33b3caa406 ***
Unpacking file(s)...		Aborted (core dumped)

**Comment by v3l0c1r4pt0r** [comment]
I suppose that this problem is the same as in issue #7 so it should have been fixed by fabf43e or 9d22a3a. Closing.
