### ISSUE TITLE
doesn't work with file in other folder

### ISSUE THREAD

**Issue by rolandg** [v3l0c1r4pt0r/xSDM#7]
$ ./xsdm ~/Downloads/de_windows_8.1_with_update_x86_dvd_4048128.01.sdc
Opening SDC file...		[OK]
Verifying keyfile...		[OK]
Validating SDC header...	[OK]
Checking file integrity...	[OK]
Decoding file name...		[OK]
*** Error in `./xsdm': malloc(): memory corruption: 0x000000000216e400 ***

moving in sdc into same folder solves the problem

**Comment by v3l0c1r4pt0r** [comment]
I found an error that might cause crash, especially on i386 platform. Please check if that helped and answer if that really helped.

**Comment by rolandg** [comment]
yes works.. thanks
